{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temporal.componentname" (list . "web") }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "temporal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        helm.sh/chart: {{ include "temporal.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ include "temporal.serviceAccount" . }}
      volumes:
        - name: {{ .Chart.Name }}-web-config
          configMap:
            name: {{ include "temporal.componentname" (list . "web") }}-config
      {{- if .Values.web.additionalVolumes }}
      {{- toYaml .Values.web.additionalVolumes | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            # NOTE: Documentation for web UI environment variables found at below link.
            # https://docs.temporal.io/references/web-ui-environment-variables
            - name: TEMPORAL_ADDRESS
              value: "{{ include "temporal.fullname" . }}-frontend.{{ .Release.Namespace }}.svc:{{ .Values.server.frontend.service.port }}"
            {{- if $.Values.web.tls}}
            - name: TEMPORAL_TLS_KEY
              value: {{ $.Values.web.tls.tlsKeyPath }}
            - name: TEMPORAL_TLS_CERT
              value: {{ $.Values.web.tls.tlsCertPath }}
            - name: TEMPORAL_TLS_CA
              value: {{ $.Values.web.tls.tlsCaPath }}
            - name: TEMPORAL_TLS_SERVER_NAME
              value: {{ $.Values.web.tls.tlsServerName }}
            - name: TEMPORAL_TLS_ENABLE_HOST_VERIFICATION
              value: {{ $.Values.web.tls.tlsEnableHostVerification | quote }}
            {{- end }}
          {{- if .Values.web.additionalEnv }}
          {{- toYaml .Values.web.additionalEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if $.Values.web.tls}}
          volumeMounts:
            - name: certs
              mountPath: {{ $.Values.web.tls.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- with .Values.web.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.additionalVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.web.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Chart.Name }}-web-config
          configMap:
            name: {{ include "temporal.componentname" (list . "web") }}-config
      {{- if $.Values.web.tls}}
        - name: certs
          secret:
            secretName: {{ $.Values.web.tls.secret }}
      {{- end }}

    {{- with .Values.web.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
