{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temporal.componentname" (list . "web") }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "temporal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        helm.sh/chart: {{ include "temporal.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ include "temporal.serviceAccount" . }}
      volumes:
        - name: {{ .Chart.Name }}-web-config
          configMap:
            name: {{ include "temporal.componentname" (list . "web") }}-config
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            {{ if eq .Values.web.image.repository "temporalio/web" }}
            - name: TEMPORAL_GRPC_ENDPOINT
              value: "{{ include "temporal.fullname" . }}-frontend.{{ .Release.Namespace }}.svc:{{ .Values.server.frontend.service.port }}"
            {{ end }}
            {{ if eq .Values.web.image.repository "temporalio/ui" }}
            - name: TEMPORAL_ADDRESS
              value: "{{ include "temporal.fullname" . }}-frontend.{{ .Release.Namespace }}.svc:{{ .Values.server.frontend.service.port }}"
            {{ end }}

            {{- if $.Values.web.tls}}
            - name: TEMPORAL_TLS_KEY_PATH
              value: {{ $.Values.web.tls.tlsKeyPath }}

            - name: TEMPORAL_TLS_CERT_PATH
              value: {{ $.Values.web.tls.tlsCertPath }}

            - name: TEMPORAL_TLS_CA_PATH
              value: {{ $.Values.web.tls.tlsCaPath }}

            - name: TEMPORAL_TLS_SERVER_NAME
              value: {{ $.Values.web.tls.tlsServerName }}

            - name: TEMPORAL_TLS_ENABLE_HOST_VERIFICATION
              value: {{ $.Values.web.tls.tlsEnableHostVerification | quote }}
            {{- end }}

          {{ if eq $.Values.web.image.repository "temporalio/web" }}
          volumeMounts:
            - name: {{ .Chart.Name }}-web-config
              mountPath: /usr/app/server/config.yml
              subPath: config.yml
          {{ end }}

          ports:
            - name: http
              {{ if eq $.Values.web.image.repository "temporalio/web" }}
              containerPort: 8088
              {{ end }}
              {{ if eq $.Values.web.image.repository "temporalio/ui" }}
              containerPort: 8080
              {{ end }}
              protocol: TCP
          {{- if $.Values.web.tls}}
          volumeMounts:
            - name: certs
              mountPath: {{ $.Values.web.tls.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $.Values.web.tls}}
      volumes:
        - name: certs
          secret:
            secretName: {{ $.Values.web.tls.secret }}
      {{- end }}

    {{- with .Values.web.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
